Add WHOC installation instructions to Hercules documentation
NREL/hercules pull request #59
Opened 2023-12-19 20:51 UTC by genevievestarke

2023-12-19 20:58 UTC, genevievestarke commented
@misi9170 Should we have them switch to develop in the installation instructions or stay with main after it's released for Q1?

2023-12-20 01:50 UTC, misi9170 commented
> @misi9170 Should we have them switch to develop in the installation instructions or stay with main after it's released for Q1?

I don't think we need to specify switching to develop is a necessary step. It could be worth putting a line in just mentioning that users wanting newer features should consider switching to develop?

2023-12-20 15:56 UTC, genevievestarke commented
Will do, that's added as a note to the documentation!

2023-12-20 16:02 UTC, misi9170 requested changes

2023-12-20 17:03 UTC, merged